name: AccountCreationClass Tests

on:
  push:
    branches: [ main, AccountCreation ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: List contents of root directory
        run: ls -R

      - name: Compile classes
        run: |
          javac -cp "./testresources/junit-platform-console-standalone-1.9.2.jar" -d ./out ./src/accountcreation/*.java ./test/accountcreation/*.java

      - name: List contents of out directory after compile
        run: ls -R out

      - name: Copy compiled classes to testresources directory
        run: |
          cp out/accountcreation/AccountCreationClass.class testresources/
          cp out/accountcreation/AccountCreationClassTest.class testresources/

      - name: List contents of testresources directory
        run: ls testresources

      - name: Run TestClass tests and create report
        run: |
          java -jar testresources/junit-platform-console-standalone-1.9.2.jar -cp "out:./testresources" --select-class accountcreation.AccountCreationClassTest
